from pathlib import Path

p = Path('spectral_ui.cpp')
s = p.read_text(encoding='utf-8')

old = '''    bool release_transport_to(double positionFrac) {\n        positionFrac = std::clamp(positionFrac, 0.0, 1.0);\n        auto pc = playback_control::get();\n        const double length = pc->playback_get_length_ex();\n        if (!pc->is_playing() || !pc->playback_can_seek() || length <= 0.0) return false;\n\n        auto transport = find_transport_service();\n        if (!transport.is_empty()) {\n            const double seconds = positionFrac * length;\n            bool ready = true;\n            try {\n                transport->release_transport(seconds);\n                pc->playback_seek(seconds);\n                ready = transport->is_position_ready(seconds);\n            } catch (...) {\n                ready = true;\n            }\n\n            m_transportReleaseTarget = positionFrac;\n            m_transportReleasePending = !ready;\n            if (!ready && !pc->is_paused()) {\n                pc->pause(true);\n                m_releasePauseOwned = true;\n            }\n            return true;\n        }\n\n        // Compatibility fallback for an older Stem Separator build.\n        pc->playback_seek(positionFrac * length);\n        resume_touch_pause_fallback();\n        return false;\n    }'''

new = '''    bool release_transport_to(double positionFrac) {\n        positionFrac = std::clamp(positionFrac, 0.0, 1.0);\n        auto pc = playback_control::get();\n        const double length = pc->playback_get_length_ex();\n        if (!pc->is_playing() || !pc->playback_can_seek() || length <= 0.0) return false;\n\n        auto transport = find_transport_service();\n        if (!transport.is_empty()) {\n            const double seconds = positionFrac * length;\n            bool ready = true;\n            const bool wasPaused = pc->is_paused();\n            bool pauseOwned = false;\n            try {\n                // Symmetric hard handoff with Reverse entry. Pause the output\n                // before changing transport/seek so queued reverse audio cannot\n                // drain for another output-buffer interval after release.\n                if (!wasPaused) {\n                    pc->pause(true);\n                    pauseOwned = true;\n                }\n\n                transport->release_transport(seconds);\n                pc->playback_seek(seconds);\n                ready = transport->is_position_ready(seconds);\n            } catch (...) {\n                ready = true;\n            }\n\n            m_transportReleaseTarget = positionFrac;\n            m_transportReleasePending = !ready;\n\n            if (!ready) {\n                // Keep only our own pause until the selected rendition is ready.\n                m_releasePauseOwned = pauseOwned;\n            } else {\n                // Original mode and already-cached stems resume immediately after\n                // the seek flush, instead of waiting for queued reverse audio.\n                if (pauseOwned && pc->is_playing() && pc->is_paused()) {\n                    pc->pause(false);\n                }\n                m_releasePauseOwned = false;\n            }\n            return true;\n        }\n\n        // Compatibility fallback for an older Stem Separator build.\n        pc->playback_seek(positionFrac * length);\n        resume_touch_pause_fallback();\n        return false;\n    }'''

if old not in s:
    raise SystemExit('release_transport_to block not found')

s = s.replace(old, new)
p.write_text(s, encoding='utf-8')
print('patched hard reverse release flush')
